// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);

		if (n <= 0) {
			System.out.println("Please enter a positive integer.");
			return;
		}

		double ratio;
		int greaterThanHalf = 0;
		int lessOrEqualToHalf = 0;

		for (int i = 0; i < n; i++) {
			double r = Math.random();
			if (r > 0.5) {
				greaterThanHalf++;
			} else {
				lessOrEqualToHalf++;
			}
		}

		int smaller = Math.min(greaterThanHalf, lessOrEqualToHalf);
        int larger = Math.max(greaterThanHalf, lessOrEqualToHalf);

        ratio = (double) smaller / larger;

		System.out.println("> 0.5: " + greaterThanHalf);
		System.out.println("<= 0.5: " + lessOrEqualToHalf);
		System.out.println("Ratio: " + ratio);


	}
}
